# Generated by Django 5.0.2 on 2024-02-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='member',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.BigIntegerField(),
        ),
    ]
