# Generated by Django 5.0.2 on 2024-02-25 17:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_remove_product_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'sell_price_objects'},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('sell_price_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
