# Generated by Django 5.0.2 on 2024-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_user',
                'ordering': ['-id'],
            },
        ),
    ]
