# Generated by Django 5.0.2 on 2024-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
